### ISSUE TITLE
[PE-D][Tester A] JSON file not secure

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-2/tp#121]
I was able to access the JSON file in the data folder directly and change the end timing for 1 of the module timings. This change was approved when I reopened the application, showing the end time could become eariler then the start time.
![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/9ee4741b-1f25-4c9a-890b-d9cdd50d16c6.png)

![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/8d92e80a-2eb3-4790-b428-a93116008900.png)

![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/a2b66e22-c63b-4f55-9e5f-b3d80a40f453.png)

![image.png](https://raw.githubusercontent.com/DominicFuMJ/ped/main/files/32449e3c-8c19-47e5-93cf-6c3f0ded1716.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: DominicFuMJ/ped#12

**Comment by yadunut** [comment]
@AY2324S2-CS2103T-W12-2/developers I guess we need to validate the input when reading from storage.

**Comment by AdityaB4** [comment]
I think this should not actually be worked on since the UG explicitly states changing the data file can break things and is to be done at the user's risk. 

The validation overhead (slowing down startup times) and the cost of implementation in terms of time are not worth it considering the project timeline - as such, I would be against working on this even to provide the particular user that reported this issue with some help. Updating label for now but would like to hear what everyone thinks @AY2324S2-CS2103T-W12-2/developers.

**Comment by blaukc** [comment]
Not at bug
